apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: vidsphere
type: Opaque

stringData:
  mongo-uri: "mongodb+srv://USERNAME:PASSWORD@cluster0.h4g1dt2.mongodb.net/node_backend_viodeotube?retryWrites=true&w=majority"
  jwt-secret: "abhijitmaitykolaghatbrainwareuniversity"