apiVersion: v1
kind: Service
metadata:
  name: vidsphere-backend-service
  namespace: vidsphere
spec:
  selector:
    app: vidsphere-backend

  ports:
    - port: 5000
      targetPort: 5000

  type: ClusterIP