apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidsphere-frontend
  namespace: vidsphere 
  labels:
    app: vidsphere-frontend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: vidsphere-frontend

  template:
    metadata:
      labels:
        app: vidsphere-frontend

    spec:
      containers:
        - name: frontend

          image: firojbabu452/vidsphere-frontend:a9afe1b620729e5baf8ee9ddfc02cc1e1e3c6f2a
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5