{{- if and .Values.backend.secret.create .Values.backend.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mongo-uri: {{ .Values.backend.secret.mongoUri | quote }}
  jwt-secret: {{ .Values.backend.secret.jwtSecret | quote }}
{{- end }}
