apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vidsphere
  namespace: argocd                   
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  project: default                  
  source:
    repoURL: 'https://github.com/firojbabu452/VidSphere_Video_Platform.git'
    targetRevision: development              
    path: VidSphere_Video_Platform/argocd/k8s                 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vidsphere          
  syncPolicy:
    automated:                           
      prune: true                        
      selfHeal: true                  
    syncOptions:
      - CreateNamespace=true     