apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vidsphere
  namespace: argocd                   
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # Ensures cascading deletion of resources
spec:
  project: default                        # The Argo CD project this app belongs to
  source:
    repoURL: 'https://github.com/firojbabu452/VidSphere_Video_Platform.git' # Your Git repository
    targetRevision: development              
    path: argocd/k8s                      # Points directly to argocd/k8s inside the repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vidsphere          
  syncPolicy:
    automated:                            
      prune: true                        
      selfHeal: true                  
    syncOptions:
      - CreateNamespace=true