apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidsphere-backend
  namespace: vidsphere 
  labels:
    app: vidsphere-backend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: vidsphere-backend

  template:
    metadata:
      labels:
        app: vidsphere-backend

    spec:
      containers:
        - name: backend
          image: firojbabu452/vidsphere-backend:60149164ae73373e57b8cfefee9d4601cd09843a

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: NODE_ENV
              value: "production"
              
            - name: CORS_ORIGIN
              value: "http://localhost:3000"

            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongo-uri

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
