apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidsphere-frontend
  namespace: vidsphere 
  labels:
    app: vidsphere-frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: vidsphere-frontend

  template:
    metadata:
      labels:
        app: vidsphere-frontend

    spec:
      containers:
        - name: frontend

          image: firojbabu452/vidsphere-frontend:60149164ae73373e57b8cfefee9d4601cd09843a
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
