name: Vidsphare cicd pipeline

on:
 push:
   branches:
     - main
     - development

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        working-directory: ./Application-Code/backend
        run: npm install

      # - name: Run backend tests
      #   working-directory: ./Application-Code/backend
      #   run: npm test
    
      - name: Install Frontend Dependencies
        working-directory: ./Application-Code/frontend
        run: npm install


      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
      #login to docker hub
      - name: Log in Docker hub 
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Backend image

      - name: Build backend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/vidsphere-backend:${{ github.sha }} \
            ./Application-Code/backend

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vidsphere-backend:${{ github.sha }}

   # Frontend image

      - name: Build frontend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/vidsphere-frontend:${{ github.sha }} \
            ./Application-Code/frontend

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vidsphere-frontend:${{ github.sha }}

      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Backend Image Tag
        run: |
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/vidsphere-backend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/vidsphere-backend:${{ github.sha }}|g" \
          argocd/k8s/backend-deployment.yml

      - name: Update Frontend Image Tag
        run: |
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/vidsphere-frontend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/vidsphere-frontend:${{ github.sha }}|g" \
          argocd/k8s/frontend-deployment.yml

      - name: Commit Manifest Changes
        run: |
          git add argocd/k8s/backend-deployment.yml
          git add argocd/k8s/frontend-deployment.yml

          git diff --cached --quiet || git commit -m "Update images to ${{ github.sha }}"

      - name: Push Manifest Changes
        run: |
          git push origin HEAD:${{ github.ref_name }}